# Welcome to Jekyll!

title: Weasel Code
email: luis.rph@protonmail.com
lang: es
description: >- 
  Blog personal sobre Programación y Software Libre
baseurl: "" 
url: "www.weaselcode.com"
twitter_username: WeaselCode
github_username:  dp-weasel

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

